sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t tmdflqdnl/contentshelper ./

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: sabana-contents-helper
  env: Sabanacontentshelper-env
  bucket_name: elasticbeanstalk-ap-northeast-2-164107959770
  bucket_path: sabana-contents-helper
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  seceret_access_key: $AWS_SECRET_ACCESS_KEY