name: deploy docker
on:
  push:
    branches: [ master ]

env:
  DOCKER_IMAGE: tmdflqdnl/

jobs:
  deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-northeast-2
    app: sabana-contents-helper
    env: Sabanacontentshelper-env
    bucket_name: elasticbeanstalk-ap-northeast-2-164107959770
    bucket_path: sabana-contents-helper
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    seceret_access_key: $AWS_SECRET_ACCESS_KEY